name: CI

on:
  push:

jobs:

  check:
    name: CI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.21

      - name: Lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.54

      - uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: '1.6.*'
          terraform_wrapper: false

      - name: Test
        run: go test -race -coverprofile=coverage.out -covermode=atomic ./...
        env:
          TF_ACC: '1'
          FORWARDEMAIL_API_KEY: ${{ secrets.FORWARDEMAIL_API_KEY }}

      - name: Upload coverage
        uses: codecov/codecov-action@v3
